gearman:
  container_name: kismia_gearman
  image: z7zmey/gearman-mysql
  links:
    - gearman_db
  environment:
    MYSQL_HOST: gearman_db
    MYSQL_USER: gearman
    MYSQL_PASSWORD: gearman
  ports:
    - "4730:4730"

gearman_db:
  container_name: kismia_gearman_db
  image: mysql:5.6
  environment:
    MYSQL_USER: gearman
    MYSQL_ROOT_PASSWORD: gearman
    MYSQL_PASSWORD: gearman
    MYSQL_DATABASE: gearman
